server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://dpg-d1ml3dje5dus73as0ca0-a.oregon-postgres.render.com:5432/microservice
    username: scm20_o9v8_user
    password: JuWIGA7KOtbPriGPSQacK6Z0XbmBpbvT
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  application:
    name: HOTEL-SERVICE

  config:
    import: configserver:https://config-server-microservices-hotel.onrender.com

#  profiles:
#    active: prod

eureka:
  instance:
    prefer-ip-address: true
    instance-id: hotel-service-microservices-hotel.onrender.com/
    status-page-url: https://hotel-service-microservices-hotel.onrender.com/actuator/info
    health-check-url: https://hotel-service-microservices-hotel.onrender.com/health
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: https://service-regsistry-microservices-hotel.onrender.com/eureka/




